WITH PullBaseRecs as
(
select
DISTINCT
	sm.AREANAME,
	job_typ_ojb,
	JOB_NO_OJB,
	ORDER_NO_OJB,
	COMPL_DTE_OJB,
	IR_TECH_OJB,
	CUST_ACCT_NO_OJB,
	JOB_COMMENTS_OJB,
	SMNAM,
	CASE WHEN REGEXP_INSTR(COMPL_CDE_OJB,'ND')>0 THEN 'Yes' ELSE 'No' END as NOT_DONE,
--	CASE WHEN (extract(DAY from TO_TIMESTAMP(TO_CHAR(COMPL_DTE_OJB ||''|| COMPL_TME_OJB),'DD/MM/YY HH24.MI.SS') - TO_TIMESTAMP(TO_CHAR(CREATE_DTE_OJB || CREATE_TME_OJB),'DD/MM/YY HH24:MI:SS'))+
--	extract(HOUR from TO_TIMESTAMP(TO_CHAR(COMPL_DTE_OJB ||''|| COMPL_TME_OJB),'DD/MM/YY HH24.MI.SS') - TO_TIMESTAMP(TO_CHAR(CREATE_DTE_OJB || CREATE_TME_OJB),'DD/MM/YY HH24:MI:SS'))/24+
--	extract(MINUTE from TO_TIMESTAMP(TO_CHAR(COMPL_DTE_OJB ||''|| COMPL_TME_OJB),'DD/MM/YY HH24.MI.SS') - TO_TIMESTAMP(TO_CHAR(CREATE_DTE_OJB || CREATE_TME_OJB),'DD/MM/YY HH24:MI:SS'))/1440) <= 1
  	CASE WHEN
	DATEDIFF(MINUTE, TO_TIMESTAMP(CREATE_DTE_OJB || ' ' || CREATE_TME_OJB, 'YYYY-MM-DD HH24.MI.SS'),TO_TIMESTAMP(COMPL_DTE_OJB || ' ' || COMPL_TME_OJB, 'YYYY-MM-DD HH24.MI.SS')) <= 1440
	THEN 1
        ELSE 0
    	END as DayFlag
from
	HSE_BASE ho
	JOIN custom.dept.NER_SITE_MAP sm ON
	(
		sm.SYS = ho.SYS_HSE
		AND sm.PRIN = ho.PRIN_HSE
		AND sm.AGENT = ho.AGNT_HSE
	)
	JOIN custom.dept.NER_WO_JOBS job ON
	(
		job.SYS_OJB = ho.SYS_HSE
		AND job.PRIN_OJB = ho.PRIN_HSE
		AND job.HSE_KEY_OJB = ho.HSE_KEY_HSE
		AND job.IR_TECh_OJB <> 0000
		AND JOB_STAT_OJB in ('C','D')
		AND JOB_CLASS_OJB = 'T'
		AND REGEXP_INSTR(JOB_TYP_OJB,'XV|XQ|XT|XU|V8')>0
		AND	COMPL_DTE_OJB >=  to_date(current_date -7) AND COMPL_DTE_OJB < current_date
	)
	JOIN custom.dept.NER_UXIDF1 emp ON
	(
		emp.SMNROV = SYS_OJB
		AND emp.SMRPNB = IR_TECH_OJB
		AND CREATE_DTE_OJB between TO_DATE(to_char(emp.WKRSD),'YYYY-MM-DD') AND COALESCE(TO_DATE(to_char(emp.WKRED),'YYYY-MM-DD'),current_date)
	)
	ORDER BY
		ORDER_NO_OJB,
		JOB_NO_OJB
)
select
	Areaname,
	Compl_Dte_OJB,
	Not_DONE,
	DayFlag,
	SUM(DayFlag)as SLA_CNT,
	COUNT(ORDER_NO_OJB) as Order_Cnt,
	TO_CHAR(SUM(DayFlag)/COUNT(ORDER_NO_OJB),'0.999') as Completedwithin24Hours
FROM
	PullBaseRecs
Group by
Areaname,
Compl_Dte_OJB,
NOT_DONE,
DayFlag
ORDER BY
	AREANAME,
	Compl_dte_OJB;