WITH PullBaseRecs as
(
select
DISTINCT
	sm.AREANAME,
	job_typ_ojb,
	JOB_NO_OJB,
	ORDER_NO_OJB,
	COMPL_DTE_OJB,
	IR_TECH_OJB,
	CUST_ACCT_NO_OJB,
	JOB_COMMENTS_OJB,
	SMNAM,
	CASE
		WHEN TO_TIMESTAMP(TO_CHAR(COMPL_DTE_OJB ||''|| COMPL_TME_OJB),'YYYY-MM-DDHH24.MI.SS') < TO_TIMESTAMP(TO_CHAR(COMPL_DTE_OJB || ' 16:00:00'),'YYYY-MM-DDHH24:MI:SS') THEN 'Before 4pm'
		ELSE 'After 4 PM'
	END as time_Cat,
	--TO_TIMESTAMP(TO_CHAR(COMPL_DTE_OJB ||''|| COMPL_TME_OJB),'DD/MM/YY HH24.MI.SS') - TO_TIMESTAMP(TO_CHAR(CREATE_DTE_OJB || '' || CREATE_TME_OJB),'DD/MM/YY HH24:MI:SS') As Time_Delta,
	DATEDIFF('Day', TO_TIMESTAMP(CREATE_DTE_OJB || '' || CREATE_TME_OJB, 'YYYY-MM-DDHH24.MI.SS'), TO_TIMESTAMP(COMPL_DTE_OJB || '' || COMPL_TME_OJB, 'YYYY-MM-DDHH24.MI.SS')) AS Time_Delta,
	CASE
		WHEN REGEXP_INSTR(emp.JOBTTL, 'CONTRACT')>0  THEN 'CONTRACTOR'
		ELSE 'IN-HOUSE'
	END as In_House_Flag
from
	custom.dept.NER_WO_JOBS
	JOIN HSE_BASE ho on
	(
		SYS_OJB = ho.SYS_HSE
		AND PRIN_OJB = ho.PRIN_HSE
		AND HSE_KEY_OJB = ho.HSE_KEY_HSE
	)
	JOIN custom.dept.NER_SITE_MAP sm ON
	(
		sm.SYS = SYS_OJB
		AND sm.PRIN = PRIN_OJB
	)
	JOIN custom.dept.NER_UXIDF1 emp ON
	(
		emp.SMNROV = SYS_OJB
		AND emp.SMRPNB = IR_TECH_OJB
		AND CREATE_DTE_OJB between TO_DATE(to_char(emp.WKRSD),'YYYY-MM-DD') AND COALESCE(TO_DATE(to_char(emp.WKRED),'YYYY-MM-DD'),current_date)
	)
WHERE
 	COMPL_DTE_OJB = to_date(current_date -1)
	AND IR_TECH_OJB <> 0000
	AND JOB_STAT_OJB in ('C','D')
	AND JOB_CLASS_OJB <> 'D'
	AND REGEXP_INSTR(JOB_TYP_OJB,'XV|XQ|XT|XU|V8|FA|GU|GW|GX|GY')>0
	--AND REGEXP_INSTR(COMPL_CDE_OJB,'ND')=0
ORDER BY
	ORDER_NO_OJB,
	JOB_NO_OJB
)
select
	Areaname,
	time_cat,
	in_House_Flag,
	cast(Order_No_OJB as VARCHAR) as Order_No_OJB,
	COMPL_DTE_OJB,
	COUNT(ORDER_NO_OJB) as order_cnt
FROM
	PullBaseRecs
WHERE
	--EXTRACT( Day from Time_Delta)>=0
	Time_Delta>=0
Group by
Areaname,
time_cat,
in_House_Flag,
Order_NO_OJB,
COMPL_DTE_OJB
ORDER BY
	AREANAME,
	TIME_CAT,
	IN_HOUSE_FLAG;